<a href="https://colab.research.google.com/github/saikrithik/Jovian-Course-Pytorch-DeepLearning/blob/main/Alexnet_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Fri Feb 19 08:13:32 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.39       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   64C    P8    11W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
from __future__ import print_function
import torch

In [3]:
#empty gives unknown uniniliazed matrix,whatever values were allocated in the memory will appear as intial values
#Here 5 and 4 represents number of rows and columns in the matrix
#whatever values appeared first,so it doesnt work like rand
a=torch.empty(5,4)
print(a)

tensor([[2.0406e-35, 0.0000e+00, 7.0065e-44, 6.8664e-44],
        [6.3058e-44, 6.7262e-44, 7.0065e-44, 6.3058e-44],
        [6.8664e-44, 7.9874e-44, 1.1771e-43, 6.7262e-44],
        [7.8473e-44, 8.1275e-44, 6.8664e-44, 7.1466e-44],
        [8.1275e-44, 7.1466e-44, 7.7071e-44, 6.4460e-44]])


In [4]:
b=torch.rand(5,4)
print(b)

tensor([[0.0516, 0.7948, 0.1267, 0.2477],
        [0.4842, 0.5433, 0.7464, 0.1769],
        [0.2408, 0.5702, 0.7308, 0.4321],
        [0.5131, 0.9061, 0.6008, 0.3738],
        [0.9793, 0.4127, 0.5426, 0.9798]])


In [5]:
c=torch.tensor([5,4])
print(c)

tensor([5, 4])


In [6]:
c=c.new_ones(5,4,dtype=torch.float)
print(c)
c=torch.randn_like(c,dtype=torch.float)
print(c)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[-0.9551,  0.1528,  1.9452,  0.7809],
        [-1.8558, -0.5392,  0.3066,  0.3107],
        [-1.3715,  2.4447, -0.4259,  0.4365],
        [-0.7531, -0.4696,  1.9839, -1.2900],
        [ 1.0509,  1.8174, -0.2245, -0.8999]])


In [7]:
d=torch.randn(5,4)
print(torch.add(c,d))

tensor([[-1.3065,  2.2575,  0.4315,  0.0348],
        [-2.2813,  0.5915,  1.1162, -0.3149],
        [-1.8640,  2.4961, -0.3316,  0.9469],
        [-0.3835, -2.5115,  4.4687, -1.4774],
        [ 1.7214,  0.5438, -2.5162, -0.4000]])


In [8]:
b=torch.empty(5,4)
c=torch.empty(5,4)
print(b)
print(c)

tensor([[2.0407e-35, 0.0000e+00, 7.0065e-44, 6.8664e-44],
        [6.3058e-44, 6.7262e-44, 7.0065e-44, 6.3058e-44],
        [6.8664e-44, 7.9874e-44, 1.1771e-43, 6.7262e-44],
        [7.8473e-44, 8.1275e-44, 6.8664e-44, 7.1466e-44],
        [8.1275e-44, 7.2868e-44, 7.4269e-44, 6.4460e-44]])
tensor([[2.0407e-35, 0.0000e+00, 1.2673e-01, 2.4771e-01],
        [4.8415e-01, 5.4333e-01, 7.4645e-01, 1.7694e-01],
        [2.4083e-01, 5.7024e-01, 7.3083e-01, 4.3208e-01],
        [5.1312e-01, 9.0606e-01, 6.0083e-01, 3.7376e-01],
        [9.7927e-01, 4.1266e-01, 5.4258e-01, 9.7981e-01]])


In [9]:
print(b.add(c))

tensor([[4.0814e-35, 0.0000e+00, 1.2673e-01, 2.4771e-01],
        [4.8415e-01, 5.4333e-01, 7.4645e-01, 1.7694e-01],
        [2.4083e-01, 5.7024e-01, 7.3083e-01, 4.3208e-01],
        [5.1312e-01, 9.0606e-01, 6.0083e-01, 3.7376e-01],
        [9.7927e-01, 4.1266e-01, 5.4258e-01, 9.7981e-01]])


In [10]:
if torch.cuda.is_available():
  device=torch.device("cuda") #a cuda object
  y=torch.ones_like(c,device=device)  #directly create a tensor on gpu
  c=c.to(device)    #move the tensor to gpu
  z=y+c
  print(z)

tensor([[1.0000, 1.0000, 1.1267, 1.2477],
        [1.4842, 1.5433, 1.7464, 1.1769],
        [1.2408, 1.5702, 1.7308, 1.4321],
        [1.5131, 1.9061, 1.6008, 1.3738],
        [1.9793, 1.4127, 1.5426, 1.9798]], device='cuda:0')


In [12]:
device

device(type='cuda', index=0)

# Alexnet neural network

In [32]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchsummary import summary
#-----------Change This according to ur req---------------
out_classes = 3
#---------------------------------------------------------

def conv_block(in_channels, out_channels,kernel=3,s=1,p=1, pool=False):
    layers = [nn.Conv2d(in_channels, out_channels, kernel_size=kernel,stride=s,padding=p), 
              nn.BatchNorm2d(out_channels), 
              nn.ReLU(inplace=True)]
    if pool: layers.append(nn.MaxPool2d(2))
    return nn.Sequential(*layers)

class neural_network(nn.Module):

  def __init__(self):
    super(neural_network,self).__init__()
    #3,224,224
    self.conv1 = conv_block(3, 96,kernel=11,s=4,p=1,pool=True) #96,54,54 --> #96,27,27
    self.conv2 = conv_block(96, 256,kernel=5,s=1,p=2,pool=True) #256,27,27 --> #256,13,13
    self.conv3= conv_block(256,384,kernel=3,s=1,p=1)#384,13,13
    self.conv4= conv_block(384,384,kernel=3,s=1,p=1)#384,13,13
    self.conv5= conv_block(384, 256,kernel=3,s=1,p=1,pool=True)#256,6,6
    self.flatten = nn.Flatten()#256*6*6
    self.drop = nn.Dropout(0.5)
    self.fc1=nn.Linear(256*6*6,4096)
    self.fc2=nn.Linear(4096,1000)
    self.fc3=nn.Linear(1000,out_classes)
    self.soft=nn.Softmax(dim=1)

  def forward(self,x):
    out = self.conv1(x)
    out = self.conv2(out)
    out = self.conv3(out)
    out = self.conv4(out)
    out = self.conv5(out)
    out = self.flatten(out)
    out = self.drop(out)
    out = self.fc1(out)
    out = self.fc2(out)
    out = self.fc3(out)
    out = self.soft(out)
    
    # x=nn.BatchNorm2d(x)
    # x=F.max_pool2d(F.relu(self.conv2(x)),(3,3),stride=2)
    # x=nn.BatchNorm2d(self.conv3(x))
    # x=nn.BatchNorm2d(self.conv4(x))
    # x=F.max_pool2d(F.relu(self.conv5(x)),(3,3),stride=2)
    # x=F.dropout(x,p=0.5)
    # x=x.view(x.size()[0],-1)
    # x=F.relu(self.fc1(x))
    # x=F.dropout(x,p=0.5)
    # x=F.relu(self.fc2(x))
    # x=self.fc3(x)
    return out

x = torch.randn(1,1,32,32)
model=neural_network()
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

x=torch.FloatTensor(x).to(device)
model=model.to(device)
summary(model,(3,224,224))


----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1           [-1, 96, 54, 54]          34,944
       BatchNorm2d-2           [-1, 96, 54, 54]             192
              ReLU-3           [-1, 96, 54, 54]               0
         MaxPool2d-4           [-1, 96, 27, 27]               0
            Conv2d-5          [-1, 256, 27, 27]         614,656
       BatchNorm2d-6          [-1, 256, 27, 27]             512
              ReLU-7          [-1, 256, 27, 27]               0
         MaxPool2d-8          [-1, 256, 13, 13]               0
            Conv2d-9          [-1, 384, 13, 13]         885,120
      BatchNorm2d-10          [-1, 384, 13, 13]             768
             ReLU-11          [-1, 384, 13, 13]               0
           Conv2d-12          [-1, 384, 13, 13]       1,327,488
      BatchNorm2d-13          [-1, 384, 13, 13]             768
             ReLU-14          [-1, 384,